# src/commands/gcloud-kubeconfig.yaml
# yamllint disable rule:line-length
---
description: Use container clusters get-credentials to generate a kubeconfig file

parameters:

  cluster-name:
    description: GKE cluster name
    type: string

  project-id:
    description: Google Cloud project ID
    type: string
    default: ""

  region:
    description: Google Cloud region
    type: string
    default: ""

  impersonate-service-account:
    description: GC service account to impersonate
    type: string
    default: ""

steps:
  - when:
      condition: << parameters.impersonate-service-account >>
      steps:
        - run:
            name: impersonate service account << parameters.impersonate-service-account >>
            command: |
              echo "impersonating << parameters.impersonate-service-account >>@<< parameters.project-id >.iam.gserviceaccount.com"
              gcloud config set auth/impersonate_service_account << parameters.impersonate-service-account >>@<< parameters.project-id >.iam.gserviceaccount.com &>/dev/null
  - run:
      name: container clusters get-credentials
      command: |
        gcloud container clusters get-credentials << parameters.cluster-name >>  \
          --project << parameters.project-id >> \
          --zone << parameters.region >>
